package core

import (
	"c2-backend/internal/db"
	"fmt"
	"strings"
	"time"
)

// GenerateMarkdownReport aggregates mission data and returns a formatted Markdown report.
func GenerateMarkdownReport(store *db.Store, sessionID int64) (string, error) {
	var report strings.Builder

	// 1. Header
	report.WriteString("# ⚔️ Duelist C2: Mission Briefing\n")
	report.WriteString(fmt.Sprintf("**Date:** %s  \n", time.Now().Format("2006-01-02 15:04:05")))

	// 2. Aggregate Data
	discoveries, _ := store.GetDiscoveries(sessionID)
	history, _ := store.GetScanHistory(sessionID)
	summaryNote, _ := store.GetNote(sessionID, "global")

	// 3. Stats & Executive Summary
	targetsCount := 0
	vulnsCount := 0
	for _, d := range discoveries {
		switch d.Type {
		case "domain", "ip":
			targetsCount++
		case "vuln":
			vulnsCount++
		}
	}

	report.WriteString("\n## 📊 Mission Overview\n")
	report.WriteString(fmt.Sprintf("- **Total Targets Identified:** %d\n", targetsCount))
	report.WriteString(fmt.Sprintf("- **Total Vulnerabilities Found:** %d\n", vulnsCount))
	report.WriteString(fmt.Sprintf("- **Engagement Tools Deployed:** %d\n", len(history)))

	report.WriteString("\n## 📝 Executive Summary\n")
	if summaryNote != "" {
		report.WriteString(summaryNote + "\n")
	} else {
		report.WriteString("No global mission summary provided by operator.\n")
	}

	// 4. Attack Surface Mapping
	report.WriteString("\n## 🛡️ Attack Surface Mapping\n")
	
	// Group services by target
	targetToServices := make(map[string][]string)
	for _, d := range discoveries {
		if d.Type == "service" {
			// Find parent target if possible via source_scan_id
			parentVal := "Unknown Target"
			for _, t := range discoveries {
				if (t.Type == "domain" || t.Type == "ip") && t.SourceScanID == d.SourceScanID {
					parentVal = t.Value
					break
				}
			}
			targetToServices[parentVal] = append(targetToServices[parentVal], d.Value)
		}
	}

	if len(targetToServices) > 0 {
		for target, services := range targetToServices {
			report.WriteString(fmt.Sprintf("### %s\n", target))
			for _, s := range services {
				report.WriteString(fmt.Sprintf("- [x] %s\n", s))
			}
			report.WriteString("\n")
		}
	} else {
		report.WriteString("No services mapped yet.\n")
	}

	// 5. Vulnerability Findings
	report.WriteString("\n## 🛑 Vulnerability Findings\n")
	hasVulns := false
	for _, d := range discoveries {
		if d.Type == "vuln" {
			report.WriteString(fmt.Sprintf("### %s\n", d.Value))
			report.WriteString(fmt.Sprintf("- **Discovery Date:** %s\n", d.CreatedAt))
			// Extract severity if present in metadata
			report.WriteString("- **Status:** Confirmed\n\n")
			hasVulns = true
		}
	}
	if !hasVulns {
		report.WriteString("No vulnerabilities identified during this engagement.\n")
	}

	// 6. Engagement Timeline
	report.WriteString("\n## ⏳ Engagement Timeline\n")
	report.WriteString("| Tool | Target | Status | Start Time |\n")
	report.WriteString("| :--- | :--- | :--- | :--- |\n")
	for _, h := range history {
		report.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", h.ToolName, h.Target, h.Status, h.StartTime))
	}

	report.WriteString("\n---\n*Report generated by Duelist C2 Strategic Intelligence Engine*")

	return report.String(), nil
}
